// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJ772yu17YjxnEs2sPoG_iv-dOM04Yko',
    appId: '1:143413968745:web:2e56b2bfd20f187f3b47f8',
    messagingSenderId: '143413968745',
    projectId: 'miniproject-ppb',
    authDomain: 'miniproject-ppb.firebaseapp.com',
    storageBucket: 'miniproject-ppb.firebasestorage.app',
    measurementId: 'G-03DSM6QJ9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2cJQSzVZzJD4z7p8wnQT8wcMM2L2K24',
    appId: '1:143413968745:android:9747ce4e03b582843b47f8',
    messagingSenderId: '143413968745',
    projectId: 'miniproject-ppb',
    storageBucket: 'miniproject-ppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTcmrJHP5eg4csQgFElMWDXgmj-JHF0u8',
    appId: '1:143413968745:ios:d478d3f4de3f41c53b47f8',
    messagingSenderId: '143413968745',
    projectId: 'miniproject-ppb',
    storageBucket: 'miniproject-ppb.firebasestorage.app',
    iosBundleId: 'com.example.miniprojectPbb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTcmrJHP5eg4csQgFElMWDXgmj-JHF0u8',
    appId: '1:143413968745:ios:d478d3f4de3f41c53b47f8',
    messagingSenderId: '143413968745',
    projectId: 'miniproject-ppb',
    storageBucket: 'miniproject-ppb.firebasestorage.app',
    iosBundleId: 'com.example.miniprojectPbb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcJ772yu17YjxnEs2sPoG_iv-dOM04Yko',
    appId: '1:143413968745:web:8b7100f4cd3a59c53b47f8',
    messagingSenderId: '143413968745',
    projectId: 'miniproject-ppb',
    authDomain: 'miniproject-ppb.firebaseapp.com',
    storageBucket: 'miniproject-ppb.firebasestorage.app',
    measurementId: 'G-S8BSR2BQLK',
  );
}
